# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ArRobotCode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArRobotCode
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'ObservableArray-RxSwift'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'PopupDialog'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'lottie-ios'

  target 'ArRobotCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArRobotCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
